CREATE  TABLE TUSER
(
     USERID      VARCHAR2(12 BYTE)  PRIMARY KEY
  ,  PASSWD      VARCHAR2(12 BYTE)
  ,  USERNAME  VARCHAR2(30 BYTE)
  ,  INDATE      DATE     DEFAULT SYSDATE
)

INSERT INTO TUSER ( USERID, PASSWD, USERNAME )
  VALUES ( 'SEA3',   '1234',   '바다3' );
INSERT INTO TUSER ( USERID, PASSWD, USERNAME )
  VALUES ( 'ironman',   '1234',   '토니 스타크' );
 COMMIT; 
